repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      -   id: trailing-whitespace
      -   id: check-ast
      -   id: pretty-format-json
      -   id: check-ast
      -   id: check-case-conflict
      -   id: check-docstring-first
      -   id: check-merge-conflict
      -   id: check-symlinks
      -   id: check-yaml
      -   id: trailing-whitespace